version: "3.9"

services:
  db:
    image: postgres:17
    container_name: betogether-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: betogether-api
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
