services:
  db:
    image: postgres:17
    container_name: betogether_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: betogether_api
    restart: always
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - "8000"

  nginx:
    image: nginx:stable-alpine
    container_name: betogether_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./admin-panel/dist:/usr/share/nginx/html/admin-panel
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: betogether_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./admin-panel/dist:/usr/share/nginx/html
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew; sleep 12h; done"

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:

